spring:
  application:
    name: orvo-service
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    servlet:
      path: /api
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://${PG_HOST:localhost}:${PG_PORT:5432}/${PG_DATABASE:orvo-service}
    username: ${PG_USERNAME:admin}
    password: ${PG_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver

orvo:
  email:
    port: 25
    username: noreply@orvoro.site
    smtp:
      connectiontimeout: 10000
      timeout: 10000
      writetimeout: 10000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
      cors:
        allowed-origins: "http://localhost:5173"
        allowed-methods: GET,POST,PUT,DELETE,OPTIONS
        allowed-headers: "*"
        allow-credentials: true

